### ISSUE TITLE
Typo in image

### ISSUE THREAD

**Issue by layflags** [shprink/web-components-todo#10]
Just to be picky ... never heard of StakeJS ;)

**Comment by shprink** [comment]
haha I know :) https://twitter.com/treshugart/status/966949327582085120 
Will update thanks :)

**Comment by shprink** [comment]
Done

![stencil_vs_wc](https://user-images.githubusercontent.com/1388706/36589944-426428b0-188d-11e8-8ce1-b0b3f39ca9d9.png)

**Comment by layflags** [comment]
:D nice!
