### ISSUE TITLE
(native) initial todo item incorrectly rendered

### ISSUE THREAD

**Issue by abennouna** [shprink/web-components-todo#12]
When you first display the native demo, the second todo item is not checked, so it is supposed to be incomplete. However, when you mark the first one as complete, the second one is marked completed as well when the component is refreshed.

Likewise, if we start by marking the second item completed, it seems it does not have any effect the first time we click.

The culprit seems to be the line ```this._checked = false;``` in TodoItem constructor.

Shouldn't it be ```this._checked = this.checked;``` ?

**Comment by shprink** [comment]
Hello,

thanks for sharing this. You were right. It is fixed now.
