### ISSUE TITLE
(stencil) inconsistent checkbox look

### ISSUE THREAD

**Issue by abennouna** [shprink/web-components-todo#13]
In the StencilJS demo, the checkboxes style needs additional styling.

Tested in:
- Chrome 64.0.3282.186 (Official build) (64 bits)
- Safari 11.0.3 (13604.5.6)

Tested:
<img width="609" alt="capture d ecran 2018-03-03 a 12 11 47" src="https://user-images.githubusercontent.com/1470318/36934152-13f5fd5e-1edd-11e8-9474-70a1a06cdce2.png">

Expected:
<img width="612" alt="capture d ecran 2018-03-03 a 12 11 40" src="https://user-images.githubusercontent.com/1470318/36934153-164c6b56-1edd-11e8-9903-203ced1e4ffa.png">

**Comment by shprink** [comment]
Fixed: https://wc-todo.firebaseapp.com/stencil/

thanks
