### ISSUE TITLE
Polymer 3 Example unchecks last item when previous item is deleted

### ISSUE THREAD

**Issue by heliostatic** [shprink/web-components-todo#19]
![2018-09-14 19 45 30](https://user-images.githubusercontent.com/70898/45579603-e3011f80-b856-11e8-995d-7de5bf67baf5.gif)

**Comment by shprink** [comment]
thanks for reporting. will get on it as soon as I can. If you have polymer 3 knowledge feel free to give it a crack.

**Comment by thepassle** [comment]
Submitted a PR that fixes this https://github.com/shprink/web-components-todo/pull/21

**Comment by shprink** [comment]
It is fixed on prod. Thanks guys
