### ISSUE TITLE
Problem running web components todo in Stencil

### ISSUE THREAD

**Issue by satyakresna** [shprink/web-components-todo#5]
Hi Julien, I just try web components todo in Stencil via local and install dependencies. When I run ```npm run dev``` the folder ```www``` overwrite by Stencil like picture below 
<img width="1436" alt="screen shot 2018-02-09 at 10 00 40 pm" src="https://user-images.githubusercontent.com/11099186/36059246-6951c612-0e6f-11e8-91ca-36279c1250de.png">
and in my terminal shows error as attached. 
<img width="978" alt="screen shot 2018-02-10 at 2 35 17 pm" src="https://user-images.githubusercontent.com/11099186/36059261-b35327f6-0e6f-11e8-9218-6d5df8039437.png">

AFAIK, the folder ```www``` is ignore by Stencil so when we run ```npm run dev``` or ```npm run start``` it will generate a folder ```www``` with it’s assets. Can I know the reason why you don't ignore this folder? Could you please advice what should I do to solve the problem? Thanks a lot.

**Comment by shprink** [comment]
The `www` was served on github before being on firebase `https://wc-todo.firebaseapp.com/stencil/www/index.html` wanted to move fast, did not want any CI build step involved. That's the reason it is commited and not ignored. Now it is on firebase, I could ignore them again. Will do next time I update this repo (maybe 2day)

As fo your compiler problem, it could be a version problem, there is no stable version yet, things are moving fast.

**Comment by satyakresna** [comment]
Hi Julien, thanks a lot for your response. Yep, you're right Stencil is not stable yet. I got information from Stencil Slack channel (sorry no SS) that sass will remove and replace with css for performance. I check in their Github, they already do that.
<img width="1002" alt="screen shot 2018-02-11 at 7 27 04 pm" src="https://user-images.githubusercontent.com/11099186/36072820-a381bca0-0f61-11e8-8bd6-8e7e36b432c0.png">

So, I'm curious and will try to move your previous stencil code to current version. I hope I can do that ASAP.

**Comment by shprink** [comment]
Cool, this afternoon I will probably finish the Vue version and if I have more time I will add SkateJS version as well

**Comment by satyakresna** [comment]
Noted. I hope I can promote this repository in my community, I will try to
share about web components and promote this as good sample.

Salam,
Satya Kresna

https://github.com/satyakresna
www.linkedin.com/in/satyakresna

**Comment by satyakresna** [comment]
Hi Julien, thanks a lot the problem of running in stencil is done. 🎉🙏

**Comment by shprink** [comment]
haha you are welcome my friend :)
