### ISSUE TITLE
Problem when running Vue TODO in local

### ISSUE THREAD

**Issue by satyakresna** [shprink/web-components-todo#6]
Hi Julien, thanks for update web components todo in vue framework. I just test it in local then run ```npm run start``` but, it shows empty. Here's is the picture + console.

<img width="1441" alt="screen shot 2018-02-13 at 5 57 41 am" src="https://user-images.githubusercontent.com/11099186/36122152-4d96e48c-1083-11e8-92f4-9aa2a75c8210.png">

<img width="1441" alt="screen shot 2018-02-13 at 5 58 12 am" src="https://user-images.githubusercontent.com/11099186/36122165-562a0ec6-1083-11e8-9b0b-072899a3f130.png">

When I test in dist folder after running ```npm run build:wc && npm run build``` it works well.

**Comment by shprink** [comment]
Fixed it. if you run `npm start` you can dev, it will live reload etc but no styles will be applied. Only `npm run build:wc` build the prod app with styles.

**Comment by satyakresna** [comment]
Thanks a lot.
